### ISSUE TITLE
ratyrate stars showing vertically instead of horizontally.

### ISSUE THREAD

**Issue by RamiroRD** [IgnacioFDM/CouchInn#1]
The only workaround so far involves editing `1st_load_framework.css.scss`

``` css
img {
  @extend .img-responsive;
  margin: 0 auto;
 }
```

to:

``` css
img {
  // @extend .img-responsive;
  margin: 0 auto;
 }
```

But this breaks the CouchInn logo and possibly a lot of other images.
